### ISSUE TITLE
Helm question

### ISSUE THREAD

**Issue by kevinjcoleman** [garden-io/rails-vote#1]
I'd like to run db-migrate on deploy with helm, whoever I cannot figure out where to put these lines. Am I missing something?
```
    dependencies:
      - db-migrate
```

**Comment by thsig** [comment]
These two lines should be added to the service spec, e.g.
```yaml
kind: Module
name: some-module
description: ...
type: container
services:
  - name: some-service
    ports:
      - name: http
        containerPort: ...
    dependencies:
      - ruby-migration
```
Hope this helps, let me know if there's anything else!
