### ISSUE TITLE
Deploy to a remote cluster is not working

### ISSUE THREAD

**Issue by CechTech** [garden-io/rails-vote#2]
Everything works fine in my local cluster but when I try to deploy to my DigitalOcean remote cluster I can't get past the db-migrate task. It's just running:

<img width="742" alt="Screenshot 2019-06-19 at 20 36 46" src="https://user-images.githubusercontent.com/21101177/59791244-f81d4a00-92d1-11e9-9b8a-525480465d8a.png">

Postgres is deployed. I guess there is something wrong with the frontend-service image. I published the image to hub.docker.com and I tried cluster-docker and local-docker modes but nothing seems to fix it.

The issue is that it's really hard to debug this. It's probably something trivial but I can't find the answer. Is there a way how to get more detailed log about where the db-migrate got stuck?

Last log entries:
```
postgres                  → 2019-06-19T16:11:34.243Z → postgres-84cd85fb8f-c6sh6 PostgreSQL init process complete; ready for start
 up.
postgres                  → 2019-06-19T16:11:34.243Z → postgres-84cd85fb8f-c6sh6
postgres                  → 2019-06-19T16:11:34.291Z → postgres-84cd85fb8f-c6sh6 LOG:  database system was shut down at 2019-06-19
 16:11:33 UTC
postgres                  → 2019-06-19T16:11:34.296Z → postgres-84cd85fb8f-c6sh6 LOG:  MultiXact member wraparound protections are
 now enabled
postgres                  → 2019-06-19T16:11:34.300Z → postgres-84cd85fb8f-c6sh6 LOG:  database system is ready to accept connecti
ons
postgres                  → 2019-06-19T16:11:34.301Z → postgres-84cd85fb8f-c6sh6 LOG:  autovacuum launcher started
```
### local-docker mode
```yaml
# rails-vote/garden.yml
kind: Project
name: vote-rails
environments:
  - name: local
    providers:
      - name: local-kubernetes
  - name: dev
    providers:
      - name: kubernetes
        context: do-fra1-rails-vote
        deploymentRegistry:
          hostname: hub.docker.com
          namespace: parsome
        imagePullSecrets:
          - name: rails-vote
defaultEnvironment: dev
```
> `parsome` is my docker hub username
> I created secret docker-registry with name `rails-vote`
### cluster-docker mode
```yaml
# rails-vote/garden.yml
kind: Project
name: vote-rails
environments:
  - name: local
    providers:
      - name: local-kubernetes
  - name: dev
    providers:
      - name: kubernetes
        context: do-fra1-rails-vote
        buildMode: cluster-docker
defaultEnvironment: dev
```
### Frontend yaml
```yaml
# rails-vote/frontend/garden.yml
kind: Module
type: container
name: frontend
image: parsome/frontend-service:latest
description: Front-end Rails service
hotReload:
  sync:
    - source:  app/
      target: /usr/src/app/app
services:
  - name: frontend
    ports:
      - name: http
        containerPort: 3000
    ingresses:
      - path: /
        port: http
        hostname: vote-rails.local.app.garden
    dependencies:
      - db-migrate
tasks:
  - name: db-migrate
    args: [rake db:migrate]
    dependencies:
      - postgres
```
